Fix import in Go example
pulumiverse/pulumi-harbor pull request #194
Opened 2023-12-06 12:26 UTC by scraly

2023-12-06 12:38 UTC, dirien commented
Can you change it in the `docs` folder too please?

2023-12-06 12:38 UTC, dirien requested changes
See comment

2023-12-06 13:15 UTC, scraly commented
done :)

2023-12-07 10:49 UTC, dirien approved these changes
LGTM! @dependabot squash and merge

2023-12-07 10:50 UTC, merged